services:
  database:
    image: postgres:16
    container_name: postgres_local
    restart: always
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: cas_local_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data_cas:/var/lib/postgresql/data

volumes:
  pg_data_cas: